version: "3.8"

services:
  db:
    image: mysql:8.0
    container_name: mysql_db
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: to_do_db
    volumes:
      - db_data:/var/lib/mysql

  backend:
    build:
      context: ./todo-backend
      dockerfile: Dockerfile
    container_name: laravel_backend
    ports:
      - "8000:8000"
    volumes:
      - ./todo-backend:/var/www
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_PORT: 3306
      DB_DATABASE: to_do_db
      DB_USERNAME: root
      DB_PASSWORD: secret

  frontend:
    build:
      context: ./todo-frontend
      dockerfile: Dockerfile
    container_name: react_frontend
    ports:
      - "3000:3000"
    volumes:
      - ./todo-frontend:/app
    depends_on:
      - backend
    stdin_open: true
    tty: true
    environment:
      - CHOKIDAR_USEPOLLING=true

volumes:
  db_data:
